<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="auth-flow"
    errors="0" failures="1" hostname="" id="" package="auth-flow" skipped="1"
    tests="3" time="1.525" timestamp="Wed, 10 May 2017 00:23:30 GMT">
  
    <testcase name="get to signup page" classname="auth-flow" time="1.046" assertions="2">

    

    
    </testcase>
  
    <testcase name="signup user and redirect to applications" classname="auth-flow" time="0.4790" assertions="2">

      <failure message="Testing if the URL contains &quot;/applications&quot;.">    at Object.signup user and redirect to applications (/home/flatironschool/Development/code/Projects/final-project/app-tracker-react/tests/auth-flow.js:20:20)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
    
    <testcase
      name="close" classname="auth-flow">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
